export const roles = ['admin', 'dispatcher', 'clerk', 'camp', 'hr'];
export const types = ['employees', 'attendance', 'equipment', 'camps', 'warehouses', 'plans', 'productionEntries', 'assignments', 'fuel', 'other', 'machineLogs', 'guests', 'campStays', 'maintenance', 'travelExpenses', 'shiftOverrides', 'mealMenus', 'mealFeedback', 'bedAssignments', 'payrollEntries'];
export const required = {
  employees: ['lastName', 'firstName', 'register', 'position'],
  attendance: ['date','employeeId','status'],
  equipment: ['parkNo', 'kind', 'model'],
  camps: ['name'],
  warehouses: ['name'],
  plans: ['name', 'startDate', 'endDate', 'targetOutput'],
  productionEntries: ['date','kind','material','amount'],
  assignments: ['date', 'title', 'shift'],
  fuel: ['date', 'kind', 'liters'],
  other: ['date', 'name', 'amount'],
  machineLogs: ['date','equipmentId','workShift','startHours','endHours','productiveHours'],
  guests: ['name','arrivalDate'],
  campStays: ['date','campId','category','count'],
  maintenance: ['date','equipmentId','reason','startTime'],
  travelExpenses: ['date','employeeId','amount'],
  shiftOverrides: ['date','replacementEmployeeId','reason'],
  mealMenus: ['date','campId','mealType','name'],
  mealFeedback: ['date','campId','employeeId','comment'],
  bedAssignments: ['employeeId','startDate'],
  payrollEntries: ['employeeId','month','half'],
};
export const permitted = {
  employees: ['code','lastName','firstName','clanName','register','civilId','phone','email','homeAddress','branch','position','baseSalary','socialSalary','insuredShare','payrollPlannedDays','bankName','bankAccount','lookupAccount','professionCode','insuredType','birthDate','gender','hireDate','validStatus','verificationNote','terminationDate','terminationReason','terminationInitiator','disciplinePercent','campId','shiftStart','shiftGroup','rotationPattern','initialDayNight','status','notes','sourceSheet','sourceRow'],
  attendance: ['date','employeeId','status','plannedHours','actualHours','campId','notes'],
  equipment: ['parkNo','kind','brand','model','vin','plateNo','site','warehouseId','owner','currentHours','fuelRate','tankCapacityLiters','status','availability','year','sourceStatus','operatorAId','operatorBId','operatorCId','operatorDId','contractNo','contractCompany','unitPriceMnt','currency','warranty','certificate','customsDocument','passport','sourceSheet','sourceRow','sourceData','notes'],
  camps: ['name','location','capacity','workType','manager','notes'],
  warehouses: ['name','location','manager','notes'],
  plans: ['name','startDate','endDate','site','warehouseId','shift','targetOutput','outputUnit','unitRevenue','requiredEquipment','equipmentNeeds','requiredWorkers','employeeIds','equipmentIds','plannedHours','plannedFuel','notes'],
  productionEntries: ['date','kind','shift','haulParkNo','excavatorParkNo','pit','block','level','material','materialType','race','dump','capacity','amount','sourceFile','sourceSheet','sourceRow','notes'],
  assignments: ['date','title','site','shift','employeeId','equipmentId','planId','campId','plannedHours','plannedFuel','plannedOutput','autoPlanId','scheduleKey','notes'],
  fuel: ['date','kind','equipmentId','parkNo','equipmentType','liters','receivedTime','motorHours','pricePerLiter','supplier','notes'],
  other: ['date','name','category','amount','notes'],
  machineLogs: ['date','equipmentId','employeeId','workShift','shiftGroup','startHours','endHours','productiveHours','moveHours','fuelingHours','noFuelHours','noOperatorHours','surveyHours','safetyHours','loadingWaitHours','engineeringHours','personalHours','safetyMeetingHours','handoverHours','mealBreakHours','repairHours','lubricationHours','readyHours','weatherHours','managementHours','startKm','endKm','startTime','endTime','stopMinutes','stopReason','operatorConfirmed','masterConfirmed','dispatcherChecked','fuelUsed','notes'],
  guests: ['name','organization','phone','register','arrivalDate','departureDate','purpose','campId','notes'],
  campStays: ['date','category','employeeId','guestId','campId','count','breakfast','lunch','dinner','mealRate','lodgingRate','rentalCompany','notes'],
  maintenance: ['date','equipmentId','reason','startTime','endTime','minutes','status','notes'],
  travelExpenses: ['date','employeeId','amount','paid','route','notes'],
  shiftOverrides: ['date','originalEmployeeId','replacementEmployeeId','shift','reason','approvedBy','notes'],
  mealMenus: ['date','campId','mealType','name','ingredients','notes'],
  mealFeedback: ['date','campId','employeeId','mealType','comment','requestedAllowance','approvedAllowance','hrStatus','hrNote','notes'],
  bedAssignments: ['employeeId','campId','building','room','bed','startDate','endDate','notes'],
  payrollEntries: ['employeeId','month','half','plannedHours','workedHours','travelDays','baseSalary','insuredShare','insuranceRate','taxRate','extraPay','otherDeduction','skipPayroll','skipReason','notes'],
};
