export default String.raw`CREATE TABLE IF NOT EXISTS public.users (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username text UNIQUE NOT NULL,
  name text NOT NULL,
  role text NOT NULL CHECK (role IN ('admin','dispatcher','clerk','camp','hr')),
  password text NOT NULL,
  active boolean NOT NULL DEFAULT true,
  camp_id integer
);

CREATE TABLE IF NOT EXISTS public.sessions (
  token text PRIMARY KEY,
  user_id integer NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  expires_at bigint NOT NULL
);

CREATE TABLE IF NOT EXISTS public.login_attempts (
  key text PRIMARY KEY,
  count integer NOT NULL,
  reset_at bigint NOT NULL
);

CREATE TABLE IF NOT EXISTS public.records (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type text NOT NULL,
  body jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS records_type_idx ON public.records(type);

CREATE TABLE IF NOT EXISTS public.submissions (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  assignment_id integer NOT NULL REFERENCES public.records(id) ON DELETE CASCADE,
  work_date date NOT NULL,
  status text NOT NULL CHECK (status IN ('done','not_done')),
  actual_hours numeric NOT NULL DEFAULT 0,
  actual_fuel numeric NOT NULL DEFAULT 0,
  actual_output numeric NOT NULL DEFAULT 0,
  note text,
  submitted_by integer NOT NULL REFERENCES public.users(id),
  submitted_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(assignment_id,work_date)
);

ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.login_attempts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.records ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.submissions ENABLE ROW LEVEL SECURITY;
`;
