export default String.raw`CREATE TABLE IF NOT EXISTS public.projects (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text UNIQUE NOT NULL,
  active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.users (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username text UNIQUE NOT NULL,
  name text NOT NULL,
  role text NOT NULL CHECK (role IN ('admin','dispatcher','clerk','camp','hr')),
  password text NOT NULL,
  active boolean NOT NULL DEFAULT true,
  camp_id integer
);
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS project_id integer REFERENCES public.projects(id);
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS employee_id integer;

CREATE TABLE IF NOT EXISTS public.role_permissions (
  project_id integer NOT NULL REFERENCES public.projects(id) ON DELETE CASCADE,
  role text NOT NULL,
  permissions jsonb NOT NULL DEFAULT '{}'::jsonb,
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY(project_id,role)
);

CREATE TABLE IF NOT EXISTS public.audit_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id integer REFERENCES public.projects(id),
  user_id integer REFERENCES public.users(id),
  username text NOT NULL,
  role text NOT NULL,
  page text NOT NULL,
  action text NOT NULL,
  record_id integer,
  details jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS audit_logs_project_time_idx ON public.audit_logs(project_id,created_at DESC);

CREATE TABLE IF NOT EXISTS public.import_batches (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id integer NOT NULL REFERENCES public.projects(id),
  type text NOT NULL,
  filename text,
  row_count integer NOT NULL,
  created_by integer REFERENCES public.users(id),
  created_at timestamptz NOT NULL DEFAULT now(),
  undone_at timestamptz
);

CREATE TABLE IF NOT EXISTS public.documents (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id integer NOT NULL REFERENCES public.projects(id),
  employee_id integer NOT NULL,
  kind text NOT NULL,
  fields jsonb NOT NULL DEFAULT '{}'::jsonb,
  approvers jsonb NOT NULL DEFAULT '[]'::jsonb,
  pdf bytea NOT NULL,
  created_by integer NOT NULL REFERENCES public.users(id),
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS documents_project_employee_idx ON public.documents(project_id,employee_id,created_at DESC);

CREATE TABLE IF NOT EXISTS public.sessions (
  token text PRIMARY KEY,
  user_id integer NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  expires_at bigint NOT NULL
);

CREATE TABLE IF NOT EXISTS public.login_attempts (
  key text PRIMARY KEY,
  count integer NOT NULL,
  reset_at bigint NOT NULL
);

CREATE TABLE IF NOT EXISTS public.records (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type text NOT NULL,
  body jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.records ADD COLUMN IF NOT EXISTS project_id integer REFERENCES public.projects(id);
ALTER TABLE public.records ADD COLUMN IF NOT EXISTS import_batch_id bigint REFERENCES public.import_batches(id);

CREATE INDEX IF NOT EXISTS records_type_idx ON public.records(type);

CREATE TABLE IF NOT EXISTS public.submissions (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  assignment_id integer NOT NULL REFERENCES public.records(id) ON DELETE CASCADE,
  work_date date NOT NULL,
  status text NOT NULL CHECK (status IN ('done','not_done')),
  actual_hours numeric NOT NULL DEFAULT 0,
  actual_fuel numeric NOT NULL DEFAULT 0,
  actual_output numeric NOT NULL DEFAULT 0,
  note text,
  submitted_by integer NOT NULL REFERENCES public.users(id),
  submitted_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(assignment_id,work_date)
);

ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.login_attempts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.records ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.submissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.role_permissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.import_batches ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.documents ENABLE ROW LEVEL SECURITY;
`;
